language: node_js
node_js:
  - node
  - lts/*

services:
  - docker
before_script:
  - docker pull linuxserver/deluge
  - docker run -d -p 8112:8112 -p 58846:58846 -p 58946:58946 --net=host linuxserver/deluge

script:
  - npm run lint
  - npm run test:ci
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run build:docs

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run build
        - npm run semantic-release
    - stage: deploy
      node_js: lts/*
      script:
        - npm run build:docs
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs
        github_token: $GH_TOKEN
        on:
          branch: master

notifications:
  email: false
